# Generated by Django 3.0.6 on 2020-06-01 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LineaProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('precio_mayorista', models.IntegerField(default=0)),
                ('precio_final', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aroma', models.CharField(max_length=30)),
                ('linea', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.LineaProducto')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.TipoProducto')),
            ],
        ),
    ]
