# Generated by Django 3.0.6 on 2020-06-02 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='nombre',
        ),
        migrations.AddField(
            model_name='clientes',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='tipo',
            field=models.CharField(choices=[('R', 'Revendedor'), ('C', 'Comercio'), ('P', 'Particular'), ('M', 'Mayorista')], default='R', max_length=1),
        ),
        migrations.DeleteModel(
            name='TiposDeCliente',
        ),
    ]
